apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-a-searchgen-10s
  labels:
    customer: a
    type: searchgen
    interval: 10s
    app: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      customer: a
      type: searchgen
      interval: 10s
  template:
    metadata:
      labels:
        customer: a
        type: searchgen
        interval: 10s
        app: saas
    spec:
      nodeSelector:
        role: splunk
      containers:
        - name: searchgen
          image: "hovu96/splunk-searchgen:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: SEARCH_GEN_SPL
              value: "| search earliest=-10m latest=now index=_internal"
            - name: SEARCH_GEN_HOST
              value: "...."
            - name: SEARCH_GEN_USER
              value: "admin"
            - name: SEARCH_GEN_PASSWORD
              value: "...."
            - name: SEARCH_GEN_SPS
              value: "0.1"
          resources:
              requests:
                cpu: 500m
                memory: 100Mi
              limits:
                cpu: 500m
                memory: 100Mi                